#!/usr/bin/env python3
"""Anti-drift tests for the committed Codex marketplace plugin mirror.

``plugins/token-optimizer/`` is the nested Codex marketplace plugin directory
regenerated from the canonical repo-root content by
``scripts/sync-codex-marketplace-plugin.sh`` (Codex CLI only resolves
marketplace plugins that live in a subdirectory, not at the repo root). The
mirror can silently drift from the source it was generated off -- a fix applied
to ``hooks/run.py`` or ``hooks/userpromptsubmit_runner.py`` at the root but not
re-mirrored is invisible until the release gate rejects it, or worse, until a
Codex user hits the stale bug.

These tests are the tripwire (analogous to the Cowork
``test_rebuild_emit_committed_leaves_git_clean`` / ``test_cowork_committed_plugin``):

  (a) rebuilding via ``sync-codex-marketplace-plugin.sh`` INTO A STAGING DIR
      reproduces the committed ``plugins/token-optimizer/`` byte for byte (no
      drift). The rebuild never runs against the working tree: a test that
      regenerates in place is a test that can destroy uncommitted work, and a
      clean ``git status`` afterwards hides the loss. And
  (b) every ``hooks/*.py`` (and ``python-launcher.sh``) in the mirror is
      byte-identical to the root copy, so a one-sided hook edit fails RED at
      edit time instead of at the release gate. ``hooks.json`` is intentionally
      NOT byte-compared here: the sync script strips the ``async`` keys Codex
      does not support, so the mirror equals the root modulo those keys (the
      staged rebuild test in (a) guards that parity end-to-end).

Run: python3 -m pytest tests/test_codex_marketplace_plugin.py -q
"""

from __future__ import annotations

import hashlib
import os
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

from _tree_parity import fingerprint, stage_inputs, tree_drift

REPO = Path(__file__).resolve().parent.parent
ROOT_HOOKS = REPO / "hooks"
MIRROR = REPO / "plugins" / "token-optimizer"
MIRROR_HOOKS = MIRROR / "hooks"
SYNC_SCRIPT = REPO / "scripts" / "sync-codex-marketplace-plugin.sh"

# hooks.json is regenerated by the sync script with the async keys stripped
# (Codex compatibility), so it is intentionally NOT byte-identical
# to the root hooks.json. The staged-rebuild parity test guards it end to end.
# Everything else under hooks/ (the .py launchers + the bash launcher) MUST be
# byte-identical.
NON_IDENTICAL = {"hooks.json"}


# Everything the sync script reads to regenerate the mirror. Staged into a
# throwaway root so the rebuild never targets the real working tree. Keep in
# step with the `cp -R` lines + the REPO_ROOT marker guard in
# scripts/sync-codex-marketplace-plugin.sh.
SYNC_INPUTS = (
    "skills",
    "hooks",
    ".codex-plugin/plugin.json",
    ".agents/plugins/marketplace.json",
)


def _relative_files(root: Path) -> set[str]:
    found = set()
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in ("__pycache__", ".pytest_cache")]
        for name in filenames:
            if name.endswith(".pyc"):
                continue
            found.add(os.path.relpath(os.path.join(dirpath, name), root))
    return found


def _digest(path: Path) -> str:
    with open(path, "rb") as handle:
        return hashlib.sha256(handle.read()).hexdigest()


# --------------------------------------------------------------------------- #
# (a) rebuild reproduces the committed mirror (no drift) -- IN A STAGING DIR
# --------------------------------------------------------------------------- #


@pytest.mark.skipif(
    sys.platform == "win32",
    reason="sync-codex-marketplace-plugin.sh is a bash release-gate step run on "
    "POSIX CI + dev machines; under Windows git-bash it emits UTF-16/exits non-zero. "
    "Windows users consume the pre-built committed mirror, they never regenerate it, "
    "so mirror reproducibility is verified on POSIX, not here.",
)
def test_rebuild_codex_marketplace_reproduces_committed_mirror(tmp_path):
    """Regenerating plugins/token-optimizer/ via the sync script must reproduce
    the committed mirror byte for byte.

    The rebuild runs against a STAGING copy of the sync inputs in tmp_path, never
    against the real working tree. The previous version of this test ran the sync
    script at the repo root and asserted ``git status`` was clean: it therefore
    ``rm -rf``'d and rewrote 125 tracked files on every suite run, silently
    discarding any uncommitted edit to the mirror (and a clean ``git status``
    afterwards made the loss invisible). Comparing the generated tree against the
    committed one proves the same property -- the mirror is exactly what the
    generator produces -- without the suite becoming a writer, without needing a
    git work tree, and with per-file drift in the failure message."""
    if not SYNC_SCRIPT.is_file():
        pytest.skip("sync-codex-marketplace-plugin.sh not present")

    before = fingerprint(MIRROR)

    stage = stage_inputs(tmp_path / "repo", REPO, SYNC_INPUTS)
    staged_script = stage / "scripts" / SYNC_SCRIPT.name
    staged_script.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(SYNC_SCRIPT, staged_script)

    proc = subprocess.run(
        ["bash", str(staged_script)],
        cwd=str(stage),
        capture_output=True,
        text=True,
        check=False,
    )
    assert proc.returncode == 0, (
        f"sync-codex-marketplace-plugin.sh failed (rc={proc.returncode}):\n"
        f"stdout:\n{proc.stdout}\nstderr:\n{proc.stderr}"
    )

    generated = stage / "plugins" / "token-optimizer"
    assert generated.is_dir(), "sync script produced no plugins/token-optimizer"

    drift = tree_drift(generated, MIRROR)
    assert not drift, (
        "the committed Codex marketplace mirror is not reproducible from "
        "scripts/sync-codex-marketplace-plugin.sh:\n"
        + "\n".join(drift)
        + "\n\nRerun `bash scripts/sync-codex-marketplace-plugin.sh` and commit "
        "the result."
    )

    # The rebuild must not have touched the real tree -- inode/mtime too, so a
    # content-identical rewrite (how the old bug hid on a clean tree) still trips.
    assert fingerprint(MIRROR) == before, (
        "this test wrote to the real plugins/token-optimizer/ mirror; the rebuild "
        "must stay inside tmp_path"
    )


# --------------------------------------------------------------------------- #
# (b) hooks/*.py (+ launcher) byte-identical to root
# --------------------------------------------------------------------------- #


def test_codex_mirror_hooks_byte_identical_to_root():
    """Every hooks file EXCEPT hooks.json must be byte-identical between the
    root and the Codex mirror. Catches a one-sided edit to run.py /
    userpromptsubmit_runner.py / module_runner.py / python-launcher.sh that the
    release gate would otherwise catch only at tag time."""
    assert ROOT_HOOKS.is_dir(), "root hooks/ missing"
    assert MIRROR_HOOKS.is_dir(), "plugins/token-optimizer/hooks/ mirror missing"

    root_files = _relative_files(ROOT_HOOKS)
    mirror_files = _relative_files(MIRROR_HOOKS)

    # The mirror must carry every root hooks file (a missing mirror file is a
    # shipping break: Codex hook setup resolves hooks via the plugin root).
    missing_in_mirror = sorted(root_files - mirror_files)
    assert not missing_in_mirror, (
        "These hooks files are missing from the Codex mirror:\n  "
        + "\n  ".join(missing_in_mirror)
        + "\n\nRerun scripts/sync-codex-marketplace-plugin.sh."
    )

    # hooks.json is intentionally different (async stripping); everything else
    # must be byte-identical.
    comparable = sorted(
        (root_files & mirror_files) - NON_IDENTICAL
    )
    assert comparable, "no comparable hooks files found -- paths are probably wrong"

    drifted = [
        rel
        for rel in comparable
        if _digest(ROOT_HOOKS / rel) != _digest(MIRROR_HOOKS / rel)
    ]
    assert not drifted, (
        "These hooks files differ between the root and the Codex mirror:\n  "
        + "\n  ".join(drifted)
        + "\n\nApply the change to the root copy AND rerun "
        "scripts/sync-codex-marketplace-plugin.sh to re-mirror:\n"
        f"  {os.path.relpath(ROOT_HOOKS, REPO)}/<file>"
    )


def test_codex_mirror_hooks_json_is_async_stipped_root():
    """hooks.json in the mirror must equal the root hooks.json under the sync
    script's two Codex compatibility transforms: every ``async`` key recursively
    removed AND SessionEnd hook timeouts clamped to Codex's 3s cap.
    Guards that the mirror's hooks.json did not drift in any OTHER respect."""
    import json

    # Must match CODEX_SESSION_END_TIMEOUT_CAP in
    # scripts/sync-codex-marketplace-plugin.sh.
    CODEX_SESSION_END_TIMEOUT_CAP = 3

    root_hj = ROOT_HOOKS / "hooks.json"
    mirror_hj = MIRROR_HOOKS / "hooks.json"
    assert root_hj.is_file() and mirror_hj.is_file()

    def _strip_async(o):
        if isinstance(o, dict):
            return {k: _strip_async(v) for k, v in o.items() if k != "async"}
        if isinstance(o, list):
            return [_strip_async(v) for v in o]
        return o

    def _clamp_session_end(doc):
        for group in doc.get("hooks", {}).get("SessionEnd", []):
            for hook in group.get("hooks", []):
                t = hook.get("timeout")
                if isinstance(t, (int, float)) and t > CODEX_SESSION_END_TIMEOUT_CAP:
                    hook["timeout"] = CODEX_SESSION_END_TIMEOUT_CAP
        return doc

    # Third sanctioned transform: launcher commands are rewritten to the Codex
    # runtime version-resolver. Undo it in the mirror before comparing so this
    # test still catches any OTHER drift.
    from _codex_mirror_norm import guard_from_resolver

    def _deresolve(o):
        if isinstance(o, dict):
            return {k: (guard_from_resolver(v) if k == "command" else _deresolve(v)) for k, v in o.items()}
        if isinstance(o, list):
            return [_deresolve(v) for v in o]
        return o

    # Fourth: the desktop status bar's hooks module is dropped (Codex loads none).
    root_doc = json.loads(root_hj.read_text(encoding="utf-8"))
    root_doc.pop("modules", None)
    expected = _clamp_session_end(_strip_async(root_doc))
    actual = _deresolve(json.loads(mirror_hj.read_text(encoding="utf-8")))
    assert actual == expected, (
        "plugins/token-optimizer/hooks/hooks.json drifted from the root "
        "hooks.json modulo the async keys, the SessionEnd timeout clamp, and the "
        "Codex resolver rewrite; rerun scripts/sync-codex-marketplace-plugin.sh."
    )
